[package]
name = "dzervit"
version = "0.3.0"
authors = ["Dimitris Zervas <dzervas@dzervas.gr>"]
edition = "2018"

[dependencies]
rocket = "0.4.10"
rocket_contrib = "0.4.7"
serde = { version = "1.0.126", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.64"
