[package]
name = "dzervit"
version = "0.1.2"
authors = ["Dimitris Zervas <dzervas@dzervas.gr>"]
edition = "2018"

[dependencies]
rocket = "0.4.6"
rocket_contrib = "0.4.6"
serde = { version = "1.0.122", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.61"
