[package]
name = "dzervit"
version = "0.3.10"
authors = ["Dimitris Zervas <dzervas@dzervas.gr>"]
edition = "2018"

[dependencies]
rocket = "0.4.11"
rocket_contrib = "0.4.10"
serde = { version = "1.0.137", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.81"
