---
{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dzervit-ingress
spec:
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressroute.host }}`)
    services:
    - kind: Service
      name: dzervit-deploy
      port: 8000
{{- end }}
