---

name: bump
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version. "major", "minor", "patch" or exact version (default: patch)'
        required: true
        default: patch

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PACKAGES_PAT }}
          fetch-depth: 0

      - name: Find last version from tag
        run: echo "LAST_VERSION=$(git describe --tags --abbrev=0 | tail -c +2 || exit 1)" >> $GITHUB_ENV
      - name: Find new version
        run: echo "NEW_VERSION=$(.github/semver-increment.sh ${{ env.LAST_VERSION }} ${{ github.event.inputs.version }} || exit 1)" >> $GITHUB_ENV

      - name: Bump Cargo.toml version
        run: 'sed -Ei "s/(^version ?= ?)\"${{ env.LAST_VERSION }}\"/\1\"${{ env.NEW_VERSION }}\"/" Cargo.toml'
      - name: Bump Chart.yaml appVersion
        run: 'sed -Ei "s/(^appVersion: ?)${{ env.LAST_VERSION }}/\1${{ env.NEW_VERSION }}/" chart/dzervit/Chart.yaml'
      - name: Bump Chart.yaml version
        run: 'sed -Ei "s/(^version: ?)${{ env.LAST_VERSION }}/\1${{ env.NEW_VERSION }}/" chart/dzervit/Chart.yaml'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Bump version to ${{ env.NEW_VERSION }}
          tagging_message: "v${{ env.NEW_VERSION }}"
          # commit_author: Dimitris Zervas <dzervas@dzervas.gr>
          # commit_user_name: Actions Bump
          # commit_user_email: bump@github.com

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.NEW_VERSION }}"
          release_name: "v${{ env.NEW_VERSION }}"
