---

name: bump
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "New version bump"
        required: true
        options:
          - major
          - minor
          - patch
        default: patch

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PACKAGES_PAT }}
          fetch-depth: 0

      - name: Find last version from tag
        run: echo "LAST_VERSION=$(git describe --tags --abbrev=0 | tail -c +2 || exit 1)" >> $GITHUB_ENV

      - name: Find new version
        uses: actions-ecosystem/action-bump-semver@v1
        id: semver
        with:
          current_version: ${{ env.LAST_VERSION }}
          level: ${{ github.event.inputs.level }}

      - name: Bump Cargo.toml version
        run: 'sed -Ei "s/(^version ?= ?)\"${{ env.LAST_VERSION }}\"/\1\"${{ steps.semver.outputs.new_version }}\"/" Cargo.toml'
      - name: Bump Chart.yaml appVersion
        run: 'sed -Ei "s/(^appVersion: ?)${{ env.LAST_VERSION }}/\1${{ steps.semver.outputs.new_version }}/" chart/dzervit/Chart.yaml'
      - name: Bump Chart.yaml version
        run: 'sed -Ei "s/(^version: ?)${{ env.LAST_VERSION }}/\1${{ steps.semver.outputs.new_version }}/" chart/dzervit/Chart.yaml'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Bump version to ${{ steps.semver.outputs.new_version }}
          tagging_message: "v${{ steps.semver.outputs.new_version }}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.semver.outputs.new_version }}"
          name: "v${{ steps.semver.outputs.new_version }}"
