---

name: deploy
on:
  deployment:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Helm install'
        uses: 'deliverybot/helm@v1'
        with:
          release: dzervit
          token: '${{ github.token }}'
          namespace: dzervit
          helm: helm3
          values: >-
            ingress:
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                cert-manager.io/cluster-issuer: letsencrypt
          chart: 'chart/dzervit'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG_PROD }}'
