---

name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test project
        run: cargo test -v

      - name: Install Tarpaulin
        uses: baptiste0928/cargo-install@v3
        if: github.ref == 'refs/heads/main'
        with:
          crate: cargo-tarpaulin
      - name: Generate coverage report
        if: github.ref == 'refs/heads/main'
        run: cargo tarpaulin --coveralls ${{ secrets.COVERALLS_TOKEN }}
